In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("IMDB Dataset.csv")

In [5]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [6]:
df.shape

(50000, 2)

In [7]:
df.head(20)

                                               review sentiment
0   One of the other reviewers has mentioned that ...  positive
1   A wonderful little production. <br /><br />The...  positive
2   I thought this was a wonderful way to spend ti...  positive
3   Basically there's a family where a little boy ...  negative
4   Petter Mattei's "Love in the Time of Money" is...  positive
5   Probably my all-time favorite movie, a story o...  positive
6   I sure would like to see a resurrection of a u...  positive
7   This show was an amazing, fresh & innovative i...  negative
8   Encouraged by the positive comments about this...  negative
9   If you like original gut wrenching laughter yo...  positive
10  Phil the Alien is one of those quirky films wh...  negative
11  I saw this movie when I was about 12 when it c...  negative
12  So im not a big fan of Boll's work but then ag...  negative
13  The cast played Shakespeare.<br /><br />Shakes...  negative
14  This a fantastic movie of three prisoners who ...  positive
15  Kind of drawn in by the erotic scenes, only to...  negative
16  Some films just simply should not be remade. T...  positive
17  This movie made it into one of my top 10 most ...  negative
18  I remember this film,it was the first film i h...  positive
19  An awful film! It must have been up against so...  negative

In [12]:
df['review'] = df['review'].str.lower()

In [14]:
df[['review']]

                                                  review
0      one of the other reviewers has mentioned that ...
1      a wonderful little production. <br /><br />the...
2      i thought this was a wonderful way to spend ti...
3      basically there's a family where a little boy ...
4      petter mattei's "love in the time of money" is...
...                                                  ...
49995  i thought this movie did a down right good job...
49996  bad plot, bad dialogue, bad acting, idiotic di...
49997  i am a catholic taught in parochial elementary...
49998  i'm going to have to disagree with the previou...
49999  no one expects the star trek movies to be high...

[50000 rows x 1 columns]

Removing html tags

In [16]:
import re
def remove_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',text)

In [17]:
df['review'] = df['review'].apply(remove_tags)

In [18]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: str